// This file is automatically generated and enhanced with resilient local storage fallback.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { DEFAULT_PARLOUR_SERVICES } from "@/lib/shop";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

// Fallback seed catalog
const FALLBACK_PRODUCTS = [
  {
    id: "prod-1",
    category: "Makeup",
    name: "Matte Liquid Lipstick",
    brand: "Rose Luxe",
    price: 399,
    image_url: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-2",
    category: "Makeup",
    name: "HD Compact Powder",
    brand: "Glow Studio",
    price: 549,
    image_url: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-3",
    category: "Makeup",
    name: "Kajal & Eyeliner Duo",
    brand: "Nayan",
    price: 249,
    image_url: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-4",
    category: "Skincare",
    name: "Vitamin C Face Serum",
    brand: "DermaPure",
    price: 699,
    image_url: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-5",
    category: "Skincare",
    name: "Aloe Hydrating Gel",
    brand: "HerbEssence",
    price: 299,
    image_url: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-6",
    category: "Skincare",
    name: "SPF 50 Sunscreen",
    brand: "SunShield",
    price: 549,
    image_url: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-7",
    category: "Haircare",
    name: "Argan Hair Oil",
    brand: "Rootz",
    price: 449,
    image_url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-8",
    category: "Haircare",
    name: "Anti-Dandruff Shampoo",
    brand: "Rootz",
    price: 379,
    image_url: "https://images.unsplash.com/photo-1631730359585-38a4935cbec4?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-9",
    category: "Fragrance",
    name: "Rose Mist Body Perfume",
    brand: "Amara",
    price: 599,
    image_url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-10",
    category: "Fragrance",
    name: "Jasmine Attar Roll-On",
    brand: "Amara",
    price: 349,
    image_url: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-11",
    category: "Tools",
    name: "Professional Makeup Brush Set",
    brand: "Blendify",
    price: 899,
    image_url: "https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=600&q=80",
    in_stock: true,
  },
  {
    id: "prod-12",
    category: "Tools",
    name: "Ceramic Hair Straightener",
    brand: "StylePro",
    price: 1599,
    image_url: "https://images.unsplash.com/photo-1633681926022-84c23e8cb2d6?w=600&q=80",
    in_stock: true,
  },
];

const FALLBACK_OFFERS = [
  {
    id: "off-1",
    title: "Bridal Season Special",
    description: "Book a bridal makeup package and get a complimentary gold facial worth ₹1100.",
    is_active: true,
  },
  {
    id: "off-2",
    title: "Free Home Tailor Visit",
    description:
      "Free measurement and cloth pickup anywhere in Lucknow on stitching orders above ₹1500.",
    is_active: true,
  },
];

const FALLBACK_DESIGNS = [
  {
    id: "des-1",
    outfit_type: "Blouses",
    name: "Designer Back-Neck Blouse",
    stitching_price: 650,
    image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&q=80",
  },
  {
    id: "des-2",
    outfit_type: "Blouses",
    name: "Princess-Cut Padded Blouse",
    stitching_price: 550,
    image_url: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?w=600&q=80",
  },
  {
    id: "des-3",
    outfit_type: "Suits",
    name: "Anarkali Suit Set",
    stitching_price: 1400,
    image_url: "https://images.unsplash.com/photo-1610030469668-8e9f34d2e5b6?w=600&q=80",
  },
  {
    id: "des-4",
    outfit_type: "Suits",
    name: "Straight Kurti with Palazzo",
    stitching_price: 900,
    image_url: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80",
  },
  {
    id: "des-5",
    outfit_type: "Dresses",
    name: "Indo-Western Gown",
    stitching_price: 2200,
    image_url: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&q=80",
  },
  {
    id: "des-6",
    outfit_type: "Dresses",
    name: "A-Line Party Dress",
    stitching_price: 1600,
    image_url: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=600&q=80",
  },
];

type FallbackUser = {
  id: string;
  email: string;
  name: string;
  phone: string;
  password?: string;
  role: string;
};

type FallbackAppointment = {
  id: string;
  user_id?: string;
  service_name?: string;
  price?: number;
  appointment_date?: string;
  time_slot?: string;
  duration_minutes?: number;
  end_time?: string;
  chair_id?: string;
  status?: string;
  payment_method?: string;
  customer_name?: string;
  customer_phone?: string;
  created_at?: string;
};

type FallbackOrder = {
  id: string;
  user_id?: string;
  items?: unknown;
  total_amount?: number;
  payment_method?: string;
  customer_name?: string;
  customer_phone?: string;
  address?: string;
  status?: string;
  created_at?: string;
};

type FallbackTailorVisit = {
  id: string;
  user_id?: string;
  customer_name?: string;
  customer_phone?: string;
  outfit_type?: string;
  address?: string;
  preferred_date?: string;
  preferred_slot?: string;
  notes?: string;
  status?: string;
  created_at?: string;
};

type FallbackOffer = {
  id: string;
  title: string;
  description: string;
  is_active: boolean;
  created_at?: string;
};

type RequestPayload = Record<string, unknown> & {
  email?: string;
  password?: string;
  title?: string;
  description?: string;
  _target_date?: string;
  data?: {
    full_name?: string;
    phone?: string;
  };
};

function getStoredJson<T>(key: string, defaultVal: T): T {
  if (typeof window === "undefined") return defaultVal;
  try {
    const raw = localStorage.getItem(key);
    return raw ? (JSON.parse(raw) as T) : defaultVal;
  } catch {
    return defaultVal;
  }
}

function setStoredJson<T>(key: string, val: T): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(key, JSON.stringify(val));
  } catch (err) {
    console.warn("Could not save to localStorage", err);
  }
}

function createLocalFallbackHandler(input: RequestInfo | URL, init?: RequestInit): Response {
  const urlStr = typeof input === "string" ? input : (input as Request).url || input.toString();
  const url = new URL(urlStr, "https://local-supabase.fallback");
  const path = url.pathname;
  const method = (init?.method || "GET").toUpperCase();

  let body: RequestPayload = {};
  if (init?.body && typeof init.body === "string") {
    try {
      body = JSON.parse(init.body) as RequestPayload;
    } catch {
      body = {};
    }
  }

  // --- Auth endpoints ---
  if (path.includes("/auth/v1/signup")) {
    const email = (body.email || "user@example.com").toLowerCase().trim();
    const name = body.data?.full_name || email.split("@")[0] || "User";
    const phone = body.data?.phone || "9876543210";
    const userId = "usr_" + Math.random().toString(36).substring(2, 10);

    const users = getStoredJson<FallbackUser[]>("sb_fallback_users", []);
    const existing = users.find((u) => u.email === email);
    const user: FallbackUser = existing || {
      id: userId,
      email,
      name,
      phone,
      password: body.password || "123456",
      role: email.includes("admin") ? "admin" : "authenticated",
    };
    if (!existing) {
      users.push(user);
      setStoredJson("sb_fallback_users", users);
    }

    const session = {
      access_token: "mock-jwt-" + user.id + "-" + Date.now(),
      token_type: "bearer",
      expires_in: 604800,
      expires_at: Math.floor(Date.now() / 1000) + 604800,
      refresh_token: "mock-ref-" + user.id,
      user: {
        id: user.id,
        aud: "authenticated",
        role: "authenticated",
        email: user.email,
        email_confirmed_at: new Date().toISOString(),
        phone: user.phone,
        user_metadata: { full_name: user.name, phone: user.phone },
        app_metadata: { provider: "email", providers: ["email"] },
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    };

    setStoredJson("sb_fallback_current_user", user);

    return new Response(JSON.stringify(session), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/auth/v1/token")) {
    const email = (body.email || "user@example.com").toLowerCase().trim();
    const users = getStoredJson<FallbackUser[]>("sb_fallback_users", []);
    let user = users.find((u) => u.email === email);

    if (!user) {
      // Auto-create for friendly demo experience
      const isAdmin = email.includes("admin");
      user = {
        id: "usr_" + Math.random().toString(36).substring(2, 10),
        email,
        name: isAdmin ? "Salon Admin" : email.split("@")[0],
        phone: "9876543210",
        password: body.password || "123456",
        role: isAdmin ? "admin" : "authenticated",
      };
      users.push(user);
      setStoredJson("sb_fallback_users", users);
    }

    const session = {
      access_token: "mock-jwt-" + user.id + "-" + Date.now(),
      token_type: "bearer",
      expires_in: 604800,
      expires_at: Math.floor(Date.now() / 1000) + 604800,
      refresh_token: "mock-ref-" + user.id,
      user: {
        id: user.id,
        aud: "authenticated",
        role: "authenticated",
        email: user.email,
        email_confirmed_at: new Date().toISOString(),
        phone: user.phone,
        user_metadata: { full_name: user.name, phone: user.phone },
        app_metadata: { provider: "email", providers: ["email"] },
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      },
    };

    setStoredJson("sb_fallback_current_user", user);

    return new Response(JSON.stringify(session), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/auth/v1/user")) {
    const currentUser = getStoredJson<FallbackUser | null>("sb_fallback_current_user", null);
    if (!currentUser) {
      return new Response(JSON.stringify({ message: "No active session" }), {
        status: 401,
        headers: { "Content-Type": "application/json" },
      });
    }
    const userPayload = {
      id: currentUser.id,
      aud: "authenticated",
      role: "authenticated",
      email: currentUser.email,
      email_confirmed_at: new Date().toISOString(),
      phone: currentUser.phone,
      user_metadata: { full_name: currentUser.name, phone: currentUser.phone },
      app_metadata: { provider: "email", providers: ["email"] },
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };
    return new Response(JSON.stringify(userPayload), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/auth/v1/logout")) {
    if (typeof window !== "undefined") {
      localStorage.removeItem("sb_fallback_current_user");
    }
    return new Response(JSON.stringify({}), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  // --- Database REST endpoints ---
  if (path.includes("/rest/v1/profiles")) {
    const currentUser = getStoredJson<FallbackUser | null>("sb_fallback_current_user", null);
    if (method === "GET") {
      if (currentUser) {
        return new Response(
          JSON.stringify([
            { id: currentUser.id, full_name: currentUser.name, phone: currentUser.phone },
          ]),
          { status: 200, headers: { "Content-Type": "application/json" } },
        );
      }
      return new Response(JSON.stringify([]), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response(JSON.stringify(body), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/rest/v1/user_roles")) {
    const currentUser = getStoredJson<FallbackUser | null>("sb_fallback_current_user", null);
    const isAdmin =
      currentUser?.email?.toLowerCase().includes("admin") || currentUser?.role === "admin";
    if (isAdmin && currentUser) {
      return new Response(JSON.stringify([{ user_id: currentUser.id, role: "admin" }]), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response(JSON.stringify([]), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/rest/v1/services")) {
    return new Response(
      JSON.stringify(
        DEFAULT_PARLOUR_SERVICES.map((s) => ({
          ...s,
          is_active: true,
          created_at: new Date().toISOString(),
        })),
      ),
      { status: 200, headers: { "Content-Type": "application/json" } },
    );
  }

  if (path.includes("/rest/v1/products")) {
    return new Response(JSON.stringify(FALLBACK_PRODUCTS), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/rest/v1/offers")) {
    const offers = getStoredJson<FallbackOffer[]>("sb_fallback_offers", FALLBACK_OFFERS);
    if (method === "POST") {
      const newOff: FallbackOffer = {
        id: "off-" + Date.now(),
        title: body.title || "Offer",
        description: body.description || "",
        is_active: true,
        created_at: new Date().toISOString(),
      };
      offers.push(newOff);
      setStoredJson("sb_fallback_offers", offers);
      return new Response(JSON.stringify(newOff), {
        status: 201,
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response(JSON.stringify(offers), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/rest/v1/boutique_designs")) {
    return new Response(JSON.stringify(FALLBACK_DESIGNS), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/rest/v1/appointments")) {
    const appointments = getStoredJson<FallbackAppointment[]>("sb_fallback_appointments", []);
    if (method === "POST") {
      const newAppt: FallbackAppointment = {
        id: "appt-" + Date.now() + "-" + Math.random().toString(36).substring(2, 6),
        created_at: new Date().toISOString(),
        status: "pending",
        ...(body as unknown as FallbackAppointment),
      };
      appointments.push(newAppt);
      setStoredJson("sb_fallback_appointments", appointments);
      return new Response(JSON.stringify(newAppt), {
        status: 201,
        headers: { "Content-Type": "application/json" },
      });
    }
    if (method === "PATCH") {
      return new Response(JSON.stringify({ updated: true }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response(JSON.stringify(appointments), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/rest/v1/orders")) {
    const orders = getStoredJson<FallbackOrder[]>("sb_fallback_orders", []);
    if (method === "POST") {
      const newOrd: FallbackOrder = {
        id: "ord-" + Date.now() + "-" + Math.random().toString(36).substring(2, 6),
        created_at: new Date().toISOString(),
        status: "pending",
        ...(body as unknown as FallbackOrder),
      };
      orders.push(newOrd);
      setStoredJson("sb_fallback_orders", orders);
      return new Response(JSON.stringify(newOrd), {
        status: 201,
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response(JSON.stringify(orders), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/rest/v1/tailor_visits")) {
    const visits = getStoredJson<FallbackTailorVisit[]>("sb_fallback_tailor_visits", []);
    if (method === "POST") {
      const newVisit: FallbackTailorVisit = {
        id: "vis-" + Date.now() + "-" + Math.random().toString(36).substring(2, 6),
        created_at: new Date().toISOString(),
        status: "pending",
        ...(body as unknown as FallbackTailorVisit),
      };
      visits.push(newVisit);
      setStoredJson("sb_fallback_tailor_visits", visits);
      return new Response(JSON.stringify(newVisit), {
        status: 201,
        headers: { "Content-Type": "application/json" },
      });
    }
    return new Response(JSON.stringify(visits), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  if (path.includes("/rest/v1/rpc/get_booked_slots")) {
    const targetDate = body._target_date;
    const appointments = getStoredJson<FallbackAppointment[]>("sb_fallback_appointments", []);
    const booked = appointments
      .filter((a) => a.appointment_date === targetDate && a.status !== "cancelled")
      .map((a) => ({
        time_slot: a.time_slot || "",
        chair_id: a.chair_id || "chair-1",
        duration_minutes: a.duration_minutes || 45,
      }));
    return new Response(JSON.stringify(booked), {
      status: 200,
      headers: { "Content-Type": "application/json" },
    });
  }

  // Default fallback response
  return new Response(JSON.stringify([]), {
    status: 200,
    headers: { "Content-Type": "application/json" },
  });
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    try {
      const res = await fetch(input, { ...init, headers });
      // If server returns 502, 503 or 404 on dead supabase URL, fallback smoothly
      if (res.status >= 500 || res.status === 404) {
        return createLocalFallbackHandler(input, init);
      }
      return res;
    } catch {
      // Network failed or offline or ENOTFOUND -> seamless local fallback
      return createLocalFallbackHandler(input, init);
    }
  };
}

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env["VITE_SUPABASE_URL"] ||
    process.env["SUPABASE_URL"] ||
    "https://gmofpyltdnplgmjkkvhb.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["SUPABASE_PUBLISHABLE_KEY"] ||
    "sb_publishable_dummy_key";

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
